spring.application.name=freelazone

spring.docker.compose.enabled=false
# ===============================
# POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/elitegames
spring.datasource.username=postgres
spring.datasource.password=antimatter

spring.datasource.driver-class-name=org.postgresql.Driver
# ===============================
# JWT STUFF
# ===============================
jwt.secret.key=W3Q6kmj9ToZloaGN3AV9XshruHdpRzy1dNOP9f7LiV1
jwt.expiration.ms=86400000
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
# ===============================
# SERVER
# ===============================
server.port=8080
# ===============================
# MAX IMAGE/FILE SIZE
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB